// guardian.js
import { callGemini } from './llmClient.js';
/**
 * The Guardian agent generates test cases for the newly written code.
 * @param {string} modernCode - The new code generated by the Architect.
 * @param {string} originalLogic - The logic description to ensure constraints are met.
 * @returns {Promise<string>} - The testing suite (e.g., Jest or Mocha tests).
 */
export async function runGuardian(modernCode, originalLogic) {
    const systemPrompt = `You are a strictly paranoid QA Automation Specialist. 
    Your job is to ensure new code is robust, handles edge cases, and exactly matches the intended business logic without introducing vulnerabilities.`;

    const userPrompt = `Review the following modernized code and the original business logic it was based on. 
    Write a comprehensive suite of unit tests (using Jest) to verify its accuracy.\n\nLogic:\n${originalLogic}\n\nNew Code:\n${modernCode}`;

    console.log("--> Guardian is writing the test suite...");
    const testCases = await callGemini(systemPrompt, userPrompt);
    
    return testCases;
}